// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDebkAdMgxyboThS2h2g9WWjE31P2xDNsc',
    appId: '1:105630708754:web:be08abcacc07d302c214cb',
    messagingSenderId: '105630708754',
    projectId: 'taskmanager-51b93',
    authDomain: 'taskmanager-51b93.firebaseapp.com',
    storageBucket: 'taskmanager-51b93.appspot.com',
    measurementId: 'G-EEDPGQE566',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWJzFAQCbr7thUvg-I164_FFGBKP4ktJk',
    appId: '1:105630708754:android:e963d34408ac1e4ec214cb',
    messagingSenderId: '105630708754',
    projectId: 'taskmanager-51b93',
    storageBucket: 'taskmanager-51b93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP_m0SesOwsJRBrwmy0-4-Oo38SgP3OQQ',
    appId: '1:105630708754:ios:492619ae7c0f10b2c214cb',
    messagingSenderId: '105630708754',
    projectId: 'taskmanager-51b93',
    storageBucket: 'taskmanager-51b93.appspot.com',
    iosBundleId: 'com.example.taskmanager1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP_m0SesOwsJRBrwmy0-4-Oo38SgP3OQQ',
    appId: '1:105630708754:ios:82c3a7d51d28f4a6c214cb',
    messagingSenderId: '105630708754',
    projectId: 'taskmanager-51b93',
    storageBucket: 'taskmanager-51b93.appspot.com',
    iosBundleId: 'com.example.taskmanager1.RunnerTests',
  );
}
